apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
        - name: tictactoe
          image: your-docker-username/tictactoe-service:latest
          ports:
            - containerPort: 8080
